### ISSUE TITLE
Only send position & counts should be published over public feed

### ISSUE THREAD

**Issue by NuttyShrimp** [12urenloop/Loxsi#17]
Currently, (almost) everything that is sent to the admin feed is also sent over the public feed, see image below.
I don't think this is intended behavior.
The public should only see the calculated counts & positions
![image](https://github.com/12urenloop/Loxsi/assets/5462901/8e265a72-7b95-4702-ac99-6928b8e1e8c4)

**Comment by FKD13** [comment]
Oof good catch, Not intended for sure

**Comment by FKD13** [comment]
@Topvennie wrote this code, and I did not catch it.

```py
class DataPublisher(QueueManager):
    """
    An extension on QueueManagers that only publishes data when it is different from last publish.
    Also provides a way to publish data to topics. This way one queue can easily be used for multiple data updates.
    """

    _cache: dict[str, Any] = {}
    _publish_lock: Lock = Lock()
```

This makes the _cache a class variable, shared between the normal and admin data publisher
